apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: demo
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: samuel@kunst.me
    privateKeySecretRef:
      name: tls-production
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
