apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-db
spec:
  # must be one, multiple instances will not share state
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-db
  template:
    metadata:
      labels:
        app: demo-app-db
      name: demo-app-db
    spec:
      containers:
        - name: demo-app-db
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: demo-app-db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "1"

      volumes:
        - name: demo-app-db-data
          persistentVolumeClaim:
            claimName: demo-app-db-volume-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app-db
  name: demo-app-db-service
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: demo-app-db
