apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    name: demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-demo
  namespace: demo
  labels:
    app: k3s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
      - image: skunst/k3s-demo
        imagePullPolicy: "Always"
        name: k3s-demo
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: svc-k3s-demo
  namespace: demo
  labels:
    app: k3s-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: k3s-demo

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k3s-demo
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-k3s-demo
            port:
              number: 80

---

