apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-staging
  namespace: demo
spec:
  secretName: tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: k8s.kunst.me
  dnsNames:
  - k8s.kunst.me
