apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-production
spec:
  secretName: tls-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: k8s.kunst.me
  dnsNames:
    - k8s.kunst.me
