apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secrets
type: Opaque
data:
  # Note: these secrets are base-64 encoded. To get the base-64 repr of a
  # string, run `echo -n "SECRET-HERE" | base64`
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  db: ZGI=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-demo
  labels:
    app: k3s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
      - image: skunst/k3s-demo
        imagePullPolicy: "Always"
        name: k3s-demo
        ports:
        - containerPort: 3000
        env:
            # value must match of the service in ./persistent-storage.yml
          - name: DB_HOST
            value: demo-app-db-service
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: demo-app-secrets
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: demo-app-secrets
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: demo-app-secrets
                key: db
          - name: DATABASE_URL
            value: postgresql://postgres:postgres@demo-app-db-service:5432/db?schema=public
          - name: NEXT_PUBLIC_API_BASE
            value: https://k8s.kunst.me/api/v1
